services:
  traccar:
    image: ghcr.io/credify-africa/traccar:sha-dd36d14
    container_name: traccar
    network_mode: "host"  # This will use the host's network directly
    volumes:
      - ./media:/app/media  # For storing media files
    environment:
      - JAVA_OPTS=-Xms512m -Xmx2048m
    restart: unless-stopped 